/* gtk4aux-x11.h generated by valac 0.56.18-dirty, the Vala compiler, do not modify */

#ifndef __GTK4AUX_X11_H__
#define __GTK4AUX_X11_H__

#include <glib-object.h>
#include <gdk/gdk.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/Xregion.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif
#define GTKAUX_X11_EWMH_TYPE_HINT_NORMAL ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_NORMAL)
#define GTKAUX_X11_EWMH_TYPE_HINT_DIALOG ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_DIALOG)
#define GTKAUX_X11_EWMH_TYPE_HINT_MENU ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_MENU)
#define GTKAUX_X11_EWMH_TYPE_HINT_TOOLBAR ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_TOOLBAR)
#define GTKAUX_X11_EWMH_TYPE_HINT_SPLASHSCREEN ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_SPLASHSCREEN)
#define GTKAUX_X11_EWMH_TYPE_HINT_UTILITY ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_UTILITY)
#define GTKAUX_X11_EWMH_TYPE_HINT_DOCK ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_DOCK)
#define GTKAUX_X11_EWMH_TYPE_HINT_DESKTOP ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_DESKTOP)
#define GTKAUX_X11_EWMH_TYPE_HINT_DROPDOWN_MENU ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_DROPDOWN_MENU)
#define GTKAUX_X11_EWMH_TYPE_HINT_POPUP_MENU ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_POPUP_MENU)
#define GTKAUX_X11_EWMH_TYPE_HINT_TOOLTIP ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_TOOLTIP)
#define GTKAUX_X11_EWMH_TYPE_HINT_NOTIFICATION ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_NOTIFICATION)
#define GTKAUX_X11_EWMH_TYPE_HINT_COMBO ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_COMBO)
#define GTKAUX_X11_EWMH_TYPE_HINT_DND ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_DND)
#define GTKAUX_X11_EWMH_TYPE_HINT_NONE ((gint) GTKAUX_X11_WINDOW_TYPE_HINT_NONE)
#define GTKAUX_X11_EWMH_STATE_HINT_NONE ((gint) GTKAUX_X11_WINDOW_STATE_HINT_NONE)
#define GTKAUX_X11_EWMH_STATE_HINT_ABOVE ((gint) GTKAUX_X11_WINDOW_STATE_HINT_ABOVE)
#define GTKAUX_X11_EWMH_STATE_HINT_BELOW ((gint) GTKAUX_X11_WINDOW_STATE_HINT_BELOW)
#define GTKAUX_X11_EWMH_STATE_HINT_MODAL ((gint) GTKAUX_X11_WINDOW_STATE_HINT_MODAL)
#define GTKAUX_X11_EWMH_STATE_HINT_STICKY ((gint) GTKAUX_X11_WINDOW_STATE_HINT_STICKY)
#define GTKAUX_X11_EWMH_STATE_HINT_SHADED ((gint) GTKAUX_X11_WINDOW_STATE_HINT_SHADED)
#define GTKAUX_X11_EWMH_STATE_HINT_SKIP_TASKBAR ((gint) GTKAUX_X11_WINDOW_STATE_HINT_SKIP_TASKBAR)
#define GTKAUX_X11_EWMH_STATE_HINT_SKIP_PAGER ((gint) GTKAUX_X11_WINDOW_STATE_HINT_SKIP_PAGER)
#define GTKAUX_X11_EWMH_STATE_HINT_MAXIMIZED_VERT ((gint) GTKAUX_X11_WINDOW_STATE_HINT_MAXIMIZED_VERT)
#define GTKAUX_X11_EWMH_STATE_HINT_MAXIMIZED_HORZ ((gint) GTKAUX_X11_WINDOW_STATE_HINT_MAXIMIZED_HORZ)
#define GTKAUX_X11_EWMH_STATE_HINT_HIDDEN ((gint) GTKAUX_X11_WINDOW_STATE_HINT_HIDDEN)
#define GTKAUX_X11_EWMH_STATE_HINT_FULLSCREEN ((gint) GTKAUX_X11_WINDOW_STATE_HINT_FULLSCREEN)
#define GTKAUX_X11_EWMH_STATE_HINT_FOCUSED ((gint) GTKAUX_X11_WINDOW_STATE_HINT_FOCUSED)
#define GTKAUX_X11_EWMH_STATE_HINT_DEMANDS_ATTENTION ((gint) GTKAUX_X11_WINDOW_STATE_HINT_DEMANDS_ATTENTION)
#define GTKAUX_X11_ALIGN_HORZ_LEFT ((gint) GTKAUX_X11_ALIGN_HORIZONTAL_LEFT)
#define GTKAUX_X11_ALIGN_HORZ_MID ((gint) GTKAUX_X11_ALIGN_HORIZONTAL_MID)
#define GTKAUX_X11_ALIGN_HORZ_RIGHT ((gint) GTKAUX_X11_ALIGN_HORIZONTAL_RIGHT)
#define GTKAUX_X11_ALIGN_VERT_TOP ((gint) GTKAUX_X11_ALIGN_VERTICAL_TOP)
#define GTKAUX_X11_ALIGN_VERT_MID ((gint) GTKAUX_X11_ALIGN_VERTICAL_MID)
#define GTKAUX_X11_ALIGN_VERT_BOTTOM ((gint) GTKAUX_X11_ALIGN_VERTICAL_BOTTOM)

typedef enum  {
	GTKAUX_X11_WINDOW_TYPE_HINT_NONE,
	GTKAUX_X11_WINDOW_TYPE_HINT_NORMAL,
	GTKAUX_X11_WINDOW_TYPE_HINT_DIALOG,
	GTKAUX_X11_WINDOW_TYPE_HINT_MENU,
	GTKAUX_X11_WINDOW_TYPE_HINT_TOOLBAR,
	GTKAUX_X11_WINDOW_TYPE_HINT_SPLASHSCREEN,
	GTKAUX_X11_WINDOW_TYPE_HINT_UTILITY,
	GTKAUX_X11_WINDOW_TYPE_HINT_DOCK,
	GTKAUX_X11_WINDOW_TYPE_HINT_DESKTOP,
	GTKAUX_X11_WINDOW_TYPE_HINT_DROPDOWN_MENU,
	GTKAUX_X11_WINDOW_TYPE_HINT_POPUP_MENU,
	GTKAUX_X11_WINDOW_TYPE_HINT_TOOLTIP,
	GTKAUX_X11_WINDOW_TYPE_HINT_NOTIFICATION,
	GTKAUX_X11_WINDOW_TYPE_HINT_COMBO,
	GTKAUX_X11_WINDOW_TYPE_HINT_DND
} GtkAuxX11WindowTypeHint;

#define GTKAUX_X11_TYPE_WINDOW_TYPE_HINT (gtkaux_x11_window_type_hint_get_type ())
typedef enum  {
	GTKAUX_X11_WINDOW_STATE_HINT_NONE,
	GTKAUX_X11_WINDOW_STATE_HINT_ABOVE,
	GTKAUX_X11_WINDOW_STATE_HINT_BELOW,
	GTKAUX_X11_WINDOW_STATE_HINT_MODAL,
	GTKAUX_X11_WINDOW_STATE_HINT_STICKY,
	GTKAUX_X11_WINDOW_STATE_HINT_SHADED,
	GTKAUX_X11_WINDOW_STATE_HINT_SKIP_TASKBAR,
	GTKAUX_X11_WINDOW_STATE_HINT_SKIP_PAGER,
	GTKAUX_X11_WINDOW_STATE_HINT_MAXIMIZED_VERT,
	GTKAUX_X11_WINDOW_STATE_HINT_MAXIMIZED_HORZ,
	GTKAUX_X11_WINDOW_STATE_HINT_HIDDEN,
	GTKAUX_X11_WINDOW_STATE_HINT_FULLSCREEN,
	GTKAUX_X11_WINDOW_STATE_HINT_FOCUSED,
	GTKAUX_X11_WINDOW_STATE_HINT_DEMANDS_ATTENTION
} GtkAuxX11WindowStateHint;

#define GTKAUX_X11_TYPE_WINDOW_STATE_HINT (gtkaux_x11_window_state_hint_get_type ())
typedef enum  {
	GTKAUX_X11_ALIGN_HORIZONTAL_LEFT,
	GTKAUX_X11_ALIGN_HORIZONTAL_MID,
	GTKAUX_X11_ALIGN_HORIZONTAL_RIGHT
} GtkAuxX11AlignHorizontal;

#define GTKAUX_X11_TYPE_ALIGN_HORIZONTAL (gtkaux_x11_align_horizontal_get_type ())
typedef enum  {
	GTKAUX_X11_ALIGN_VERTICAL_TOP,
	GTKAUX_X11_ALIGN_VERTICAL_MID,
	GTKAUX_X11_ALIGN_VERTICAL_BOTTOM
} GtkAuxX11AlignVertical;

#define GTKAUX_X11_TYPE_ALIGN_VERTICAL (gtkaux_x11_align_vertical_get_type ())
typedef enum  {
	GDKLEGACY_WINDOW_TYPE_HINT_NORMAL,
	GDKLEGACY_WINDOW_TYPE_HINT_DIALOG,
	GDKLEGACY_WINDOW_TYPE_HINT_MENU,
	GDKLEGACY_WINDOW_TYPE_HINT_TOOLBAR,
	GDKLEGACY_WINDOW_TYPE_HINT_SPLASHSCREEN,
	GDKLEGACY_WINDOW_TYPE_HINT_UTILITY,
	GDKLEGACY_WINDOW_TYPE_HINT_DOCK,
	GDKLEGACY_WINDOW_TYPE_HINT_DESKTOP,
	GDKLEGACY_WINDOW_TYPE_HINT_DROPDOWN_MENU,
	GDKLEGACY_WINDOW_TYPE_HINT_POPUP_MENU,
	GDKLEGACY_WINDOW_TYPE_HINT_TOOLTIP,
	GDKLEGACY_WINDOW_TYPE_HINT_NOTIFICATION,
	GDKLEGACY_WINDOW_TYPE_HINT_COMBO,
	GDKLEGACY_WINDOW_TYPE_HINT_DND
} GdkLegacyWindowTypeHint;

#define GDKLEGACY_TYPE_WINDOW_TYPE_HINT (gdklegacy_window_type_hint_get_type ())

VALA_EXTERN GdkDisplay* gtkaux_get_display (GObject* win_item);
VALA_EXTERN Display* gtkaux_x11_get_xdisplay (GObject* window);
VALA_EXTERN Window gtkaux_x11_get_xid (GObject* window);
VALA_EXTERN void gtkaux_x11_get_attrs (GObject* window,
                           XWindowAttributes* result);
VALA_EXTERN gboolean gtkaux_x11_get_override_redirect (GObject* window);
VALA_EXTERN void gtkaux_x11_set_override_redirect (GObject* window,
                                       gboolean enable);
VALA_EXTERN gint* gtkaux_x11_get_desktop_number (GObject* window);
VALA_EXTERN void gtkaux_x11_set_desktop_number (GObject* window,
                                    gint desktop_number);
VALA_EXTERN gboolean gtkaux_x11_is_hint_supported_by_string (GObject* window,
                                                 const gchar* hint_str);
VALA_EXTERN gboolean gtkaux_x11_is_hint_enabled_by_string (GObject* window,
                                               const gchar* hint_str,
                                               const gchar* hint_type_str);
VALA_EXTERN void gtkaux_x11_set_hint_by_string (GObject* window,
                                    const gchar* hint_str,
                                    const gchar* hint_type_str,
                                    gboolean enable);
VALA_EXTERN gboolean gtkaux_x11_is_window_type_hint_supported_by_string (GObject* window,
                                                             const gchar* window_type_hint_str);
VALA_EXTERN gchar* gtkaux_x11_get_window_type_hint_by_string (GObject* window);
VALA_EXTERN void gtkaux_x11_set_window_type_hint_by_string (GObject* window,
                                                const gchar* window_type_hint_str);
VALA_EXTERN gboolean gtkaux_x11_is_window_state_hint_supported_by_string (GObject* window,
                                                              const gchar* window_state_hint_str);
VALA_EXTERN gboolean gtkaux_x11_get_window_state_hint_by_string (GObject* window,
                                                     const gchar* window_state_hint_str);
VALA_EXTERN void gtkaux_x11_set_window_state_hint_by_string (GObject* window,
                                                 const gchar* window_state_hint_str,
                                                 gboolean enable);
VALA_EXTERN GType gtkaux_x11_window_type_hint_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gchar* gtkaux_x11_window_type_hint_to_string (GtkAuxX11WindowTypeHint self);
VALA_EXTERN GtkAuxX11WindowTypeHint gtkaux_x11_window_type_hint_parse (const gchar* window_type_str);
VALA_EXTERN gchar* gtkaux_x11_window_type_hint_int_to_string (gint window_type_hint);
VALA_EXTERN gint gtkaux_x11_window_type_hint_parse_to_int (const gchar* window_type_str);
VALA_EXTERN GType gtkaux_x11_window_state_hint_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gchar* gtkaux_x11_window_state_hint_to_string (GtkAuxX11WindowStateHint self);
VALA_EXTERN GtkAuxX11WindowStateHint gtkaux_x11_window_state_hint_parse (const gchar* window_state_str);
VALA_EXTERN gchar* gtkaux_x11_window_state_hint_int_to_string (gint window_state_hint);
VALA_EXTERN gint gtkaux_x11_window_state_hint_parse_to_int (const gchar* window_state_str);
VALA_EXTERN gboolean gtkaux_x11_is_window_type_hint_supported (GObject* window,
                                                   gint window_type_hint);
VALA_EXTERN gint gtkaux_x11_get_window_type_hint (GObject* window);
VALA_EXTERN void gtkaux_x11_set_window_type_hint (GObject* window,
                                      gint window_type_hint);
VALA_EXTERN gboolean gtkaux_x11_is_window_state_hint_supported (GObject* window,
                                                    gint window_state_hint);
VALA_EXTERN gboolean gtkaux_x11_get_window_state_hint (GObject* window,
                                           gint window_state_hint);
VALA_EXTERN void gtkaux_x11_set_window_state_hint (GObject* window,
                                       gint window_state_hint,
                                       gboolean enable);
VALA_EXTERN GType gtkaux_x11_align_horizontal_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType gtkaux_x11_align_vertical_get_type (void) G_GNUC_CONST ;
VALA_EXTERN void gtkaux_x11_move (GObject* window,
                      gint x,
                      gint y);
VALA_EXTERN void gtkaux_x11_resize (GObject* window,
                        gint width,
                        gint height);
VALA_EXTERN void gtkaux_x11_move_resize (GObject* window,
                             gint x,
                             gint y,
                             gint width,
                             gint height);
VALA_EXTERN void gtkaux_x11_get_position (GObject* window,
                              gint* x,
                              gint* y);
VALA_EXTERN void gtkaux_x11_get_size (GObject* window,
                          gint* width,
                          gint* height);
VALA_EXTERN void gtkaux_x11_get_geometry (GObject* window,
                              gint* x,
                              gint* y,
                              gint* width,
                              gint* height);
VALA_EXTERN void gtkaux_x11_get_monitor_geometry (GObject* window,
                                      gint* x,
                                      gint* y,
                                      gint* width,
                                      gint* height);
VALA_EXTERN void gtkaux_x11_set_position (GObject* window,
                              gint x,
                              gint y,
                              gint align_horz,
                              gint align_vert);
VALA_EXTERN void gtkaux_x11_set_size (GObject* window,
                          gint width,
                          gint height,
                          gint align_horz,
                          gint align_vert);
VALA_EXTERN void gtkaux_x11_set_geometry (GObject* window,
                              gint x,
                              gint y,
                              gint width,
                              gint height,
                              gint align_horz,
                              gint align_vert);
VALA_EXTERN void gtkaux_x11_get_screen_margin (GObject* window,
                                   gint* top,
                                   gint* right,
                                   gint* bottom,
                                   gint* left);
VALA_EXTERN GObject** gtkaux_x11_get_margin_array (GdkDisplay* display,
                                       gint* result_length1);
VALA_EXTERN void gtkaux_x11_get_total_margin (GdkDisplay* display,
                                  gint* top,
                                  gint* right,
                                  gint* bottom,
                                  gint* left);
VALA_EXTERN void gtkaux_x11_set_screen_margin (GObject* window,
                                   gint top,
                                   gint right,
                                   gint bottom,
                                   gint left);
VALA_EXTERN void gtkaux_x11_set_screen_margin_advanced (GObject* window,
                                            GValue* margin_top,
                                            GValue* margin_right,
                                            GValue* margin_bottom,
                                            GValue* margin_left);
VALA_EXTERN void gtkaux_x11_set_geometry_advanced (GObject* window,
                                       GValue* x,
                                       GValue* y,
                                       GValue* width,
                                       GValue* height,
                                       GValue* margin_top,
                                       GValue* margin_right,
                                       GValue* margin_bottom,
                                       GValue* margin_left,
                                       gint align_horz,
                                       gint align_vert);
VALA_EXTERN void gtkaux_x11_set_size_advanced (GObject* window,
                                   GValue* width,
                                   GValue* height,
                                   GValue* margin_top,
                                   GValue* margin_right,
                                   GValue* margin_bottom,
                                   GValue* margin_left,
                                   gint align_horz,
                                   gint align_vert);
VALA_EXTERN void gtkaux_x11_set_position_advanced (GObject* window,
                                       GValue* x,
                                       GValue* y,
                                       GValue* margin_top,
                                       GValue* margin_right,
                                       GValue* margin_bottom,
                                       GValue* margin_left,
                                       gint align_horz,
                                       gint align_vert);
VALA_EXTERN GType gdklegacy_window_type_hint_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gchar* gdklegacy_window_type_hint_to_string (GdkLegacyWindowTypeHint window_type);
VALA_EXTERN GdkLegacyWindowTypeHint gdklegacy_window_type_hint_parse (const gchar* window_type_str);
VALA_EXTERN void gdklegacy_set_modal_hint (GdkSurface* _self_,
                               gboolean modal);
VALA_EXTERN gboolean gdklegacy_get_modal_hint (GdkSurface* _self_);
VALA_EXTERN void gdklegacy_set_keep_above (GdkSurface* _self_,
                               gboolean setting);
VALA_EXTERN void gdklegacy_set_keep_below (GdkSurface* _self_,
                               gboolean setting);
VALA_EXTERN void gdklegacy_sitck (GdkSurface* _self_);
VALA_EXTERN void gdklegacy_unsitck (GdkSurface* _self_);
VALA_EXTERN void gdklegacy_set_skip_taskbar_hint (GdkSurface* _self_,
                                      gboolean skip_taskbar);
VALA_EXTERN void gdklegacy_set_skip_pager_hint (GdkSurface* _self_,
                                    gboolean skip_pager);
VALA_EXTERN gint gdklegacy_get_width (GdkSurface* _self_);
VALA_EXTERN gint gdklegacy_get_height (GdkSurface* _self_);
VALA_EXTERN void gdklegacy_get_position (GdkSurface* _self_,
                             gint* x,
                             gint* y);
VALA_EXTERN void gdklegacy_get_geometry (GdkSurface* _self_,
                             gint* x,
                             gint* y,
                             gint* width,
                             gint* height);
VALA_EXTERN void gdklegacy_move (GdkSurface* _self_,
                     gint x,
                     gint y);
VALA_EXTERN void gdklegacy_resize (GdkSurface* _self_,
                       gint width,
                       gint height);
VALA_EXTERN void gdklegacy_move_resize (GdkSurface* _self_,
                            gint x,
                            gint y,
                            gint width,
                            gint height);
VALA_EXTERN void gtklegacy_set_keep_above (GtkWindow* _self_,
                               gboolean setting);
VALA_EXTERN void gtklegacy_set_keep_below (GtkWindow* _self_,
                               gboolean setting);
VALA_EXTERN void gtklegacy_sitck (GtkWindow* _self_);
VALA_EXTERN void gtklegacy_unsitck (GtkWindow* _self_);
VALA_EXTERN void gtklegacy_set_skip_taskbar_hint (GtkWindow* _self_,
                                      gboolean skip_taskbar);
VALA_EXTERN void gtklegacy_set_skip_pager_hint (GtkWindow* _self_,
                                    gboolean skip_pager);
VALA_EXTERN gboolean gtklegacy_get_skip_taskbar_hint (GtkWindow* _self_,
                                          gboolean skip_taskbar);
VALA_EXTERN gboolean gtklegacy_get_skip_pager_hint (GtkWindow* _self_,
                                        gboolean skip_pager);
VALA_EXTERN void gtklegacy_move (GtkWindow* _self_,
                     gint x,
                     gint y);
VALA_EXTERN void gtklegacy_resize (GtkWindow* _self_,
                       gint width,
                       gint height);
VALA_EXTERN void gtklegacy_move_resize (GtkWindow* _self_,
                            gint x,
                            gint y,
                            gint width,
                            gint height);
VALA_EXTERN void gtklegacy_iconify (GtkWindow* _self_);
VALA_EXTERN void gtklegacy_unminimize (GtkWindow* _self_);
VALA_EXTERN GdkDisplay* gtkaux_gtk_get_display (GtkWindow* window);
VALA_EXTERN Display* gtkaux_gtk_x11_get_xdisplay (GtkWindow* window);
VALA_EXTERN Window gtkaux_gtk_x11_get_xid (GtkWindow* window);
VALA_EXTERN void gtkaux_gtk_x11_get_monitor_geometry (GtkWindow* window,
                                          gint* x,
                                          gint* y,
                                          gint* width,
                                          gint* height);
VALA_EXTERN gboolean gtkaux_gtk_x11_get_override_redirect (GtkWindow* window);
VALA_EXTERN void gtkaux_gtk_x11_set_override_redirect (GtkWindow* window,
                                           gboolean enable);
VALA_EXTERN gint* gtkaux_gtk_x11_get_desktop_number (GtkWindow* window);
VALA_EXTERN void gtkaux_gtk_x11_set_desktop_number (GtkWindow* window,
                                        gint desktop_number);
VALA_EXTERN gint gtkaux_gtk_x11_get_window_type_hint (GtkWindow* window);
VALA_EXTERN void gtkaux_gtk_x11_set_window_type_hint (GtkWindow* window,
                                          gint window_type_hint);
VALA_EXTERN gboolean gtkaux_gtk_x11_get_window_state_hint (GtkWindow* window,
                                               gint window_state_hint);
VALA_EXTERN void gtkaux_gtk_x11_set_window_state_hint (GtkWindow* window,
                                           gint window_state_hint,
                                           gboolean enable);
VALA_EXTERN void gtkaux_gtk_x11_set_screen_margin_advanced (GtkWindow* window,
                                                GValue* margin_top,
                                                GValue* margin_right,
                                                GValue* margin_bottom,
                                                GValue* margin_left);
VALA_EXTERN void gtkaux_gtk_x11_set_screen_margin (GtkWindow* window,
                                       gint margin_top,
                                       gint margin_right,
                                       gint margin_bottom,
                                       gint margin_left);
VALA_EXTERN void gtkaux_gtk_x11_set_geometry_advanced (GtkWindow* window,
                                           GValue* x,
                                           GValue* y,
                                           GValue* width,
                                           GValue* height,
                                           GValue* margin_top,
                                           GValue* margin_right,
                                           GValue* margin_bottom,
                                           GValue* margin_left,
                                           gint align_horz,
                                           gint align_vert);
VALA_EXTERN void gtkaux_gtk_x11_set_geometry (GtkWindow* window,
                                  gint x,
                                  gint y,
                                  gint width,
                                  gint height,
                                  gint align_horz,
                                  gint align_vert);
VALA_EXTERN void gtkaux_gtk_x11_set_size_advanced (GtkWindow* window,
                                       GValue* width,
                                       GValue* height,
                                       GValue* margin_top,
                                       GValue* margin_right,
                                       GValue* margin_bottom,
                                       GValue* margin_left,
                                       gint align_horz,
                                       gint align_vert);
VALA_EXTERN void gtkaux_gtk_x11_set_position_advanced (GtkWindow* window,
                                           GValue* x,
                                           GValue* y,
                                           GValue* margin_top,
                                           GValue* margin_right,
                                           GValue* margin_bottom,
                                           GValue* margin_left,
                                           gint align_horz,
                                           gint align_vert);
VALA_EXTERN void gtkaux_gtk_x11_set_size (GtkWindow* window,
                              gint width,
                              gint height,
                              gint align_horz,
                              gint align_vert);
VALA_EXTERN void gtkaux_gtk_x11_set_position (GtkWindow* window,
                                  gint x,
                                  gint y,
                                  gint align_horz,
                                  gint align_vert);
VALA_EXTERN void gtkaux_gtk_x11_move (GtkWindow* window,
                          gint x,
                          gint y);
VALA_EXTERN void gtkaux_gtk_x11_resize (GtkWindow* window,
                            gint width,
                            gint height);
VALA_EXTERN void gtkaux_gtk_x11_move_resize (GtkWindow* window,
                                 gint x,
                                 gint y,
                                 gint width,
                                 gint height);
VALA_EXTERN void gtkaux_gtk_set_modal (GtkWindow* window,
                           gboolean enable);
VALA_EXTERN gboolean gtkaux_gtk_get_modal (GtkWindow* window,
                               gboolean enable);
VALA_EXTERN void gtkaux_gtk_set_maximize (GtkWindow* window,
                              gboolean enable);
VALA_EXTERN void gtkaux_gtk_set_fullscreen (GtkWindow* window,
                                gboolean enable);
VALA_EXTERN void gtkaux_gtk_set_minimize (GtkWindow* window,
                              gboolean enable);
VALA_EXTERN gboolean gtkaux_gtk_x11_get_keep_above (GtkWindow* window);
VALA_EXTERN void gtkaux_gtk_x11_set_keep_above (GtkWindow* window,
                                    gboolean enable);
VALA_EXTERN gboolean gtkaux_gtk_x11_get_keep_below (GtkWindow* window);
VALA_EXTERN void gtkaux_gtk_x11_set_keep_below (GtkWindow* window,
                                    gboolean enable);
VALA_EXTERN gboolean gtkaux_gtk_x11_get_sticky (GtkWindow* window);
VALA_EXTERN void gtkaux_gtk_x11_set_sticky (GtkWindow* window,
                                gboolean enable);
VALA_EXTERN void gtkaux_gtk_x11_set_skip_taskbar (GtkWindow* window,
                                      gboolean enable);
VALA_EXTERN void gtkaux_gtk_x11_set_skip_pager (GtkWindow* window,
                                    gboolean enable);
VALA_EXTERN gboolean gtkaux_gdk_x11_get_override_redirect (GdkSurface* surface);
VALA_EXTERN void gtkaux_gdk_x11_set_override_redirect (GdkSurface* surface,
                                           gboolean enable);
VALA_EXTERN void gtkaux_gdk_x11_get_screen_margin (GdkSurface* surface,
                                       gint* top,
                                       gint* right,
                                       gint* bottom,
                                       gint* left);
VALA_EXTERN void gtkaux_gdk_x11_set_screen_margin (GdkSurface* surface,
                                       gint top,
                                       gint right,
                                       gint bottom,
                                       gint left);
VALA_EXTERN gint* gtkaux_gdk_x11_get_desktop_number (GdkSurface* surface);
VALA_EXTERN void gtkaux_gdk_x11_set_desktop_number (GdkSurface* surface,
                                        gint desktop_number);
VALA_EXTERN void gtkaux_gdk_set_modal (GdkSurface* surface,
                           gboolean enable);
VALA_EXTERN gboolean gtkaux_gdk_x11_is_keep_above_supported (GdkSurface* surface);
VALA_EXTERN gboolean gtkaux_gdk_x11_get_keep_above (GdkSurface* surface);
VALA_EXTERN void gtkaux_gdk_x11_set_keep_above (GdkSurface* surface,
                                    gboolean enable);
VALA_EXTERN gboolean gtkaux_gdk_x11_is_keep_below_supported (GdkSurface* surface);
VALA_EXTERN gboolean gtkaux_gdk_x11_get_keep_below (GdkSurface* surface);
VALA_EXTERN void gtkaux_gdk_x11_set_keep_below (GdkSurface* surface,
                                    gboolean enable);
VALA_EXTERN gboolean gtkaux_gdk_x11_is_sticky_supported (GdkSurface* surface);
VALA_EXTERN gboolean gtkaux_gdk_x11_get_sticky (GdkSurface* surface);
VALA_EXTERN void gtkaux_gdk_x11_set_sticky (GdkSurface* surface,
                                gboolean enable);
VALA_EXTERN void gtkaux_gdk_x11_set_skip_taskbar (GdkSurface* surface,
                                      gboolean enable);
VALA_EXTERN void gtkaux_gdk_x11_set_skip_pager (GdkSurface* surface,
                                    gboolean enable);
VALA_EXTERN gboolean gtkaux_gdk_x11_is_hint_supported_by_string (GdkSurface* surface,
                                                     const gchar* hint_str);
VALA_EXTERN gboolean gtkaux_gdk_x11_is_hint_enabled_by_string (GdkSurface* surface,
                                                   const gchar* hint_str,
                                                   const gchar* hint_type_str);
VALA_EXTERN void gtkaux_gdk_x11_set_hint_by_string (GdkSurface* surface,
                                        const gchar* hint_str,
                                        const gchar* hint_type_str,
                                        gboolean enable);
VALA_EXTERN gboolean gtkaux_gdk_x11_is_window_type_hint_supported (GdkSurface* surface,
                                                       gint window_type_hint);
VALA_EXTERN gint gtkaux_gdk_x11_get_window_type_hint (GdkSurface* surface);
VALA_EXTERN void gtkaux_gdk_x11_set_window_type_hint (GdkSurface* surface,
                                          gint window_type_hint);
VALA_EXTERN gboolean gtkaux_gdk_x11_is_window_state_hint_supported (GdkSurface* surface,
                                                        gint window_state_hint);
VALA_EXTERN gboolean gtkaux_gdk_x11_get_window_state_hint (GdkSurface* surface,
                                               gint window_state_hint);
VALA_EXTERN void gtkaux_gdk_x11_set_window_state_hint (GdkSurface* surface,
                                           gint window_state_hint,
                                           gboolean enable);
VALA_EXTERN GdkDisplay* gtkaux_gdk_get_display (GdkSurface* surface);
VALA_EXTERN Display* gtkaux_gdk_x11_get_xdisplay (GdkSurface* surface);
VALA_EXTERN Window gtkaux_gdk_x11_get_xid (GdkSurface* surface);
VALA_EXTERN void gtkaux_gdk_x11_get_monitor_geometry (GdkSurface* surface,
                                          gint* x,
                                          gint* y,
                                          gint* width,
                                          gint* height);
VALA_EXTERN void gtkaux_gdk_x11_get_position (GdkSurface* surface,
                                  gint* x,
                                  gint* y);
VALA_EXTERN void gtkaux_gdk_x11_set_position (GdkSurface* surface,
                                  gint x,
                                  gint y,
                                  gint align_horz,
                                  gint align_vert);
VALA_EXTERN void gtkaux_gdk_x11_get_size (GdkSurface* surface,
                              gint* width,
                              gint* height);
VALA_EXTERN void gtkaux_gdk_x11_set_size (GdkSurface* surface,
                              gint width,
                              gint height,
                              gint align_horz,
                              gint align_vert);
VALA_EXTERN void gtkaux_gdk_x11_get_geometry (GdkSurface* surface,
                                  gint* x,
                                  gint* y,
                                  gint* width,
                                  gint* height);
VALA_EXTERN void gtkaux_gdk_x11_set_geometry (GdkSurface* surface,
                                  gint x,
                                  gint y,
                                  gint width,
                                  gint height,
                                  gint align_horz,
                                  gint align_vert);
VALA_EXTERN void gtkaux_gdk_x11_move (GdkSurface* surface,
                          gint x,
                          gint y);
VALA_EXTERN void gtkaux_gdk_x11_resize (GdkSurface* surface,
                            gint width,
                            gint height);
VALA_EXTERN void gtkaux_gdk_x11_move_resize (GdkSurface* surface,
                                 gint x,
                                 gint y,
                                 gint width,
                                 gint height);
VALA_EXTERN void gtkaux_gdk_x11_set_position_advanced (GdkSurface* surface,
                                           GValue* x,
                                           GValue* y,
                                           GValue* margin_top,
                                           GValue* margin_right,
                                           GValue* margin_bottom,
                                           GValue* margin_left,
                                           gint align_horz,
                                           gint align_vert);
VALA_EXTERN void gtkaux_gdk_x11_set_size_advanced (GdkSurface* surface,
                                       GValue* width,
                                       GValue* height,
                                       GValue* margin_top,
                                       GValue* margin_right,
                                       GValue* margin_bottom,
                                       GValue* margin_left,
                                       gint align_horz,
                                       gint align_vert);
VALA_EXTERN void gtkaux_gdk_x11_set_geometry_advanced (GdkSurface* surface,
                                           GValue* x,
                                           GValue* y,
                                           GValue* width,
                                           GValue* height,
                                           GValue* margin_top,
                                           GValue* margin_right,
                                           GValue* margin_bottom,
                                           GValue* margin_left,
                                           gint align_horz,
                                           gint align_vert);
VALA_EXTERN void gtkaux_gdk_x11_set_screen_margin_advanced (GdkSurface* surface,
                                                GValue* margin_top,
                                                GValue* margin_right,
                                                GValue* margin_bottom,
                                                GValue* margin_left);

G_END_DECLS

#endif
